/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAggregatedCommodityDistributionView: typeof import('./src/components/TheAggregatedCommodityDistributionView.vue')['default']
    TheAggregatedVesselMovementView: typeof import('./src/components/TheAggregatedVesselMovementView.vue')['default']
    TheCommodityDistrbutionView: typeof import('./src/components/TheCommodityDistrbutionView.vue')['default']
    TheCommodityDistributionMap: typeof import('./src/components/TheCommodityDistributionMap.vue')['default']
    TheCommodityDistributionView: typeof import('./src/components/TheCommodityDistributionView.vue')['default']
    TheCommodityDistributionView2: typeof import('./src/components/TheCommodityDistributionView2.vue')['default']
    TheCommodityDistributionView3: typeof import('./src/components/TheCommodityDistributionView3.vue')['default']
    TheCommodityDistributionView4: typeof import('./src/components/TheCommodityDistributionView4.vue')['default']
    TheCommodityLegend: typeof import('./src/components/TheCommodityLegend.vue')['default']
    TheCommodityLocationHeatmap: typeof import('./src/components/TheCommodityLocationHeatmap.vue')['default']
    TheCommodityScatterPlot: typeof import('./src/components/TheCommodityScatterPlot.vue')['default']
    TheCommoditySelector: typeof import('./src/components/TheCommoditySelector.vue')['default']
    TheCommodityVesselHeatmap: typeof import('./src/components/TheCommodityVesselHeatmap.vue')['default']
    TheComponent: typeof import('./src/components/TheComponent.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheDateSelector: typeof import('./src/components/TheDateSelector.vue')['default']
    TheFocusODChord: typeof import('./src/components/TheFocusODChord.vue')['default']
    TheFocusVesselMovementMap: typeof import('./src/components/TheFocusVesselMovementMap.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheLocationLegend: typeof import('./src/components/TheLocationLegend.vue')['default']
    TheLocationSelector: typeof import('./src/components/TheLocationSelector.vue')['default']
    TheMainView: typeof import('./src/components/TheMainView.vue')['default']
    TheMainView2: typeof import('./src/components/TheMainView2.vue')['default']
    TheMatchResults: typeof import('./src/components/TheMatchResults.vue')['default']
    TheODChord: typeof import('./src/components/TheODChord.vue')['default']
    ThePairPanel: typeof import('./src/components/ThePairPanel.vue')['default']
    TheRegionAverageDurationView: typeof import('./src/components/TheRegionAverageDurationView.vue')['default']
    TheStaticView: typeof import('./src/components/TheStaticView.vue')['default']
    TheVesselCommoditRelationBox: typeof import('./src/components/TheVesselCommoditRelationBox.vue')['default']
    TheVesselCommodityHeatmap: typeof import('./src/components/TheVesselCommodityHeatmap.vue')['default']
    TheVesselCommodityPairBox: typeof import('./src/components/TheVesselCommodityPairBox.vue')['default']
    TheVesselCommodityRelationBox: typeof import('./src/components/TheVesselCommodityRelationBox.vue')['default']
    TheVesselCommodityRelationPanel: typeof import('./src/components/TheVesselCommodityRelationPanel.vue')['default']
    TheVesselCommodityUnionBox: typeof import('./src/components/TheVesselCommodityUnionBox.vue')['default']
    TheVesselLineChart: typeof import('./src/components/TheVesselLineChart.vue')['default']
    TheVesselLocationHeatmap: typeof import('./src/components/TheVesselLocationHeatmap.vue')['default']
    TheVesselLocationHeatmap2: typeof import('./src/components/TheVesselLocationHeatmap2.vue')['default']
    TheVesselMovementMap: typeof import('./src/components/TheVesselMovementMap.vue')['default']
    TheVesselSelector: typeof import('./src/components/TheVesselSelector.vue')['default']
    TheVesselTSNE: typeof import('./src/components/TheVesselTSNE.vue')['default']
    TheVesselTypeLegend: typeof import('./src/components/TheVesselTypeLegend.vue')['default']
  }
}
